### ISSUE TITLE
Duplicate update of freshclam definitions

### ISSUE THREAD

**Issue by dcarley** [alphagov/puppet-clamav#1]
The `clamav::run_freshclam` class may not be necessary on Ubuntu 12.04, so long as we have our ordering correct. The package install appears to update the definitions itself - resulting in both running parallel.

/cc @rjw1 @alext

**Comment by alext** [comment]
The trouble is that the freshclam daemon does the update in the background, and until it's complete the clamav daemon will fail to start.  By doing it interactively from puppet we can delay the install of the clamav-daemon package until the initial download has completed.

**Comment by alext** [comment]
I guess another approach could be to ship some out-of-date definitions with this module.  These would allow clamav-daemon to start, and then leave freshclam to update them in the background.

**Comment by deanwilson** [comment]
This module is no longer in use so we're going to close the existing issues and archive the repository. Thank you for your interest in this module. (And writing most of our puppet code base)
